version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: sonarcloud-integration:SONAR_TOKEN

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - mvn install
  build:
    commands:
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=springbootappdemo_api-service
      - sleep 5
  post_build:
    commands:
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=springbootappdemo_api-service >result.json
      - if [[ "$(jq -r '.projectStatus.status' result.json)" == "ERROR" ]] ; then CODEBUILD_BUILD_SUCCEEDING=0 ;fi
cache:
  paths:
     - '/root/.m2/**/*'